northwind:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: nsbnpck-rub28302

      # User/password auth
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: accountadmin
      database: northwind
      warehouse: compute_wh
      schema: raw
      threads: 8
      client_session_keep_alive: False